accessing
exception: anException

	exception := anException